import uuid

from typing import Optional
from pydantic import BaseModel, Field
from pydantic.json_schema import SkipJsonSchema
from ..config.prompts import Neo4jNodeCategory, NEO4J_NODE_CATEGORIES


CONTENT_NODE_CATEGORY = "Content"
CONTENT_NODE_DESCRIPTION = "Original document. Sources related content chunk nodes."
CONTENT_NODE_EDGE_NAME = "CONTENT_SOURCE_OF_NODE"
CONTENT_CHUNK_NODE_CATEGORY = "ContentChunk"
CONTENT_CHUNK_NODE_DESCRIPTION = "Chunk of original document. Sources related nodes."
CONTENT_CHUNK_NODE_EDGE_NAME = "CONTENT_CHUNK_SOURCE_OF_NODE"


### Base Classes


class BaseNode(BaseModel):
    name: str = Field(..., description="Name of the node. It should be descriptive and unique. Use CamelCase.")
    category: str = Field(..., description=f"One of the following categories: {str(NEO4J_NODE_CATEGORIES)}")
    description: str = Field(..., description="A short description of the node that is more verbose than the name.")
    created_at: str = Field(..., description="The datetime the node was created in 'YYYY-MM-DD HH:MM:SS'")
    updated_at: str = Field(..., description="The datetime of when the node was last updated.")
    node_id: SkipJsonSchema[str] = Field(
        ..., default_factory=lambda: str(uuid.uuid4()), description="The unique uuid of the node."
    )
    embedding: SkipJsonSchema[list[float]] = Field(
        [], description="The text embedding for the node. This comprises the name and description."
    )

    __hash__ = object.__hash__


class BaseEdge(BaseModel):
    source: str = Field(..., description="Source name of the node that the edge begins from.")
    source_node_id: SkipJsonSchema[str] = Field("", description="The unique uuid of the source node.")
    target: str = Field(..., description="Destination name of the node that the edge terminates in.")
    target_node_id: SkipJsonSchema[str] = Field("", description="The unique uuid of the target node.")
    name: str = Field(..., description="The edge's name representing its meaning")

    __hash__ = object.__hash__


class Node(BaseNode):
    other_fields: dict[str, str] = Field(
        default="",
        description="This could be any other fields or dicts related to this node that don't fit well into other node attributes and contains useful information. This could be columns of a date table, contact information for team members, etc.",
    )


class Edge(BaseEdge):
    other_fields: dict[str, str] = Field(
        default="",
        description="This could be any other fields or dicts related to this edge that don't fit well into other edge attributes and contains useful information. This could be the type of join between two tables, the date of a decision, etc.",
    )


### Specific Nodes


class BusinessProcessNode(BaseNode):
    category: SkipJsonSchema[str] = Field(
        Neo4jNodeCategory.BUSINESS_PROCESSES.value, description="The category of the node."
    )
    status: str = Field(..., description="The status of the process. Could be active, inactive, or archived.")
    frequency: str = Field(..., description="The frequency of the process. Could be daily, weekly, monthly, etc.")


class DecisionNode(BaseNode):
    category: SkipJsonSchema[str] = Field(
        Neo4jNodeCategory.BUSINESS_DECISIONS.value, description="The category of the node."
    )
    decision_id: SkipJsonSchema[str] = Field(
        default="", description="The unique identifier of the decision generated by the platform."
    )
    description: str = Field(
        ...,
        description="A short and specific description of the node that is more verbose than the name, and MUST CONTAIN the decision itself and context about the reason for the decision. If there is no reason you will be sad, and you don't want to be sad.",
    )
    status: str = Field(
        ...,
        description="""The status of the decision.
        ONLY ONE of: 'undecided' or 'decided'.
        'undecided' decisions are those that have not been made yet.
        'decided' decisions are those that have been made.""",
    )
    impact: str = Field(
        ...,
        description="The impact of the decision based on the content available. ONLY ONE of: 'high', 'medium', or 'low'.",
    )
    decision_type: str = Field(
        ...,
        description="The type of decision based on the content available. ONLY ONE of: 'strategic', 'tactical', or 'operational'.",
    )
    reversibility: str = Field(
        ...,
        description="The reversibility of the decision based on the content available and your intuitiion. ONLY ONE of: 'reversible' or 'irreversible'.",
    )


class OrganizationNode(BaseNode):
    category: SkipJsonSchema[str] = Field(
        Neo4jNodeCategory.ORGANIZATIONS.value, description="The category of the node."
    )
    location: str = Field(..., description="The location of the organization.")
    industry: str = Field(..., description="The industry of the organization.")
    org_type: str = Field(
        ...,
        description="The type of organization as it relates to our business. Could be customer, partner, vendor, etc.",
    )


class PeopleNode(BaseNode):
    category: SkipJsonSchema[str] = Field(Neo4jNodeCategory.PEOPLE.value, description="The category of the node.")
    title: str = Field(..., description="The title of the person in their role.")
    location: str = Field(..., description="The location of the person.")


class BusinessToolNode(BaseNode):
    category: SkipJsonSchema[str] = Field(
        Neo4jNodeCategory.BUSINESS_TOOLS.value, description="The category of the node."
    )
    url: str = Field(..., description="The URL of the tool.")
    price: str = Field(..., description="The price of the tool. Could be the purchase price or subscription price.")
    purchase_type: str = Field(
        ..., description="The type of purchase for the tool. Could be one-time or subscription."
    )


class UserNode(BaseNode):
    category: SkipJsonSchema[str] = Field(Neo4jNodeCategory.USERS.value, description="The category of the node.")
    title: str = Field(..., description="The employment title of the User in their role.")
    location: str = Field(..., description="The location of the User.")
    department: str = Field(..., description="The employment department of the User.")


class OptionNode(BaseNode):
    category: SkipJsonSchema[str] = Field(Neo4jNodeCategory.OPTIONS.value, description="The category of the node.")


class CriteriaNode(BaseNode):
    category: SkipJsonSchema[str] = Field(Neo4jNodeCategory.CRITERIA.value, description="The category of the node.")


class InsightNode(BaseNode):
    category: SkipJsonSchema[str] = Field(Neo4jNodeCategory.INSIGHTS.value, description="The category of the node.")


class GoalNode(BaseNode):
    category: SkipJsonSchema[str] = Field(Neo4jNodeCategory.GOALS.value, description="The category of the node.")
    goal_type: str = Field(
        ..., description="The type of goal. Could be financial, operational efficiency, growth, employee satisfaction."
    )


### Structured Node for catch all above


class StructuredNode(BaseModel):
    node_category: Neo4jNodeCategory = Field(
        ..., description="The category of the node - must correspond with the related node field."
    )

    people_node: Optional[PeopleNode] = Field(None, description="Nodes used to represent people in the organization.")

    tool_node: Optional[BusinessToolNode] = Field(
        None, description="Nodes used to represent tools used in the organization."
    )

    org_node: Optional[OrganizationNode] = Field(None, description="Nodes used to represent organizations as a whole.")

    decision_node: Optional[DecisionNode] = Field(
        None,
        description="Nodes used to represent decisions that ARE EXPLICITLY idenfitifed as decisions by the organization in the provided context and are undecided or decided in the organization.",
    )

    processes_node: Optional[BusinessProcessNode] = Field(
        None, description="Nodes used to represent processes in the organization."
    )

    users_node: Optional[UserNode] = Field(None, description="Nodes used to represent employees of Convictional.")

    criteria_node: Optional[CriteriaNode] = Field(
        None, description="Nodes used to represent criteria used in decision making."
    )

    options_node: Optional[OptionNode] = Field(
        None, description="Nodes used to represent options considered in decision making."
    )

    insights_node: Optional[InsightNode] = Field(
        None, description="Nodes used to represent insights in the organization."
    )

    goals_node: Optional[GoalNode] = Field(None, description="Nodes used to represent goals in the organization.")

    __hash__ = object.__hash__


CAT_TO_ATT = {
    Neo4jNodeCategory.PEOPLE: "people_node",
    Neo4jNodeCategory.BUSINESS_TOOLS: "tool_node",
    Neo4jNodeCategory.ORGANIZATIONS: "org_node",
    Neo4jNodeCategory.BUSINESS_DECISIONS: "decision_node",
    Neo4jNodeCategory.BUSINESS_PROCESSES: "processes_node",
    Neo4jNodeCategory.USERS: "users_node",
    Neo4jNodeCategory.CRITERIA: "criteria_node",
    Neo4jNodeCategory.OPTIONS: "options_node",
    Neo4jNodeCategory.INSIGHTS: "insights_node",
    Neo4jNodeCategory.GOALS: "goals_node",
}
