"""Parallel node agent for generating child nodes in DAG construction."""

import logging
from typing import List

from openai import AsyncOpenAI

from common.instruct_llm import ainstruct_llm
from common.embeddings import aembed_query
from common.prompt_template_engine import build_prompt

from ..models import DecisionNode, NodeType, BuildContext
from ..schemas import SimplifiedChildNodesSchema
from ..settings import settings

logger = logging.getLogger(__name__)


class ParallelNodeAgent:
    """Agent responsible for processing a single node and generating its children."""

    def __init__(self, node: DecisionNode, context: BuildContext):
        self.node = node
        self.context = context
        self._openai_client: AsyncOpenAI | None = None

    def _get_openai_client(self) -> AsyncOpenAI:
        """Get or create OpenAI client for embeddings."""
        if not self._openai_client:
            self._openai_client = AsyncOpenAI(api_key=settings.openai_api_key.get_secret_value())
        return self._openai_client

    async def process(self) -> List[DecisionNode]:
        """
        Process the node and generate child nodes.

        Returns:
            List of child nodes
        """
        try:
            # Enrich current node with embedding if not present
            await self._enrich_node()

            # Generate child nodes
            children = await self._generate_children()

            # Validate generated children
            validated_children = self._validate_children(children)

            return validated_children

        except Exception as e:
            logger.error(f"Error processing node {self.node.id}: {e}")
            raise

    async def _enrich_node(self) -> None:
        """Enrich the current node with embeddings if not present."""
        if self.node.embedding is None:
            try:
                text_content = f"{self.node.title}. {self.node.description}"
                embedding = await aembed_query(
                    async_openai_client=self._get_openai_client(),
                    text=text_content,
                    embedding_model=settings.embedding_model,
                    embedding_dim=1536,
                )
                self.node.embedding = embedding
            except Exception as e:
                logger.warning(f"Failed to generate embedding for node {self.node.id}: {e}")
                # Continue without embedding

    async def _generate_children(self) -> List[DecisionNode]:
        """Generate child nodes using LLM."""
        # Determine child type and layer based on alternating pattern
        child_type = NodeType.OPTION if self.node.type == NodeType.DECISION else NodeType.DECISION
        child_layer = self.node.layer + 1

        # Build prompts using template engine
        system_prompt = self._build_system_prompt(child_type, child_layer)
        user_prompt = self._build_user_prompt(child_type, child_layer)

        # Generate structured response using common LLM utility
        response = await ainstruct_llm(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            response_model=SimplifiedChildNodesSchema,
            llm_model=settings.llm_model,
            temperature=settings.generation_temperature,
            max_tokens=4000,
        )

        # Convert response to DecisionNode objects
        children = []
        for child_data in response.child_nodes:
            # Create full DecisionNode from simplified version
            # Note: id is auto-generated by DecisionNode's default_factory
            child_node = DecisionNode(
                layer=child_data.layer,
                type=child_data.type,
                title=child_data.title,
                description=child_data.description,
                decision_type=child_data.decision_type,
                reasoning_type=child_data.reasoning_type,
                goal_impacts=child_data.goal_impacts,
                tags=child_data.tags,
                metadata={
                    **child_data.metadata,
                    "parent_id": self.node.id,
                    "generation_confidence": response.confidence,
                    "generation_reasoning": response.reasoning,
                },
                confidence_score=child_data.confidence_score,
                # Fields to be populated later:
                # - embedding: will be generated in enrichment pass
                # - people_impacted: will be added in enrichment pass
                # - resource_requirements: will be added in enrichment pass
            )
            children.append(child_node)

        return children

    def _build_system_prompt(self, child_type: NodeType, child_layer: int) -> str:
        """Build system prompt using template engine."""
        try:
            return build_prompt(
                "node_generation_system.txt.jinja",
                min_children=settings.min_children_per_node,
                max_children=settings.max_children_per_node,
                problem_statement=self.context.problem_statement,
                parent_type=self.node.type.value,
                parent_layer=self.node.layer,
                child_type=child_type.value,
                child_layer=child_layer,
                parent_title=self.node.title,
                parent_description=self.node.description,
                organizational_goals=self.context.organizational_goals,
                activity_insights=self.context.activity_insights,
                past_decisions=getattr(self.context, "past_decisions", []),
                relevant_content=getattr(self.context, "relevant_content", []),
                dag_context=self._get_dag_context(),
                sibling_context=self._get_sibling_context(),
            )
        except Exception as e:
            logger.error(f"Error building system prompt: {e}")
            # Fallback to simple prompt
            return self._build_fallback_system_prompt(child_type, child_layer)

    def _build_user_prompt(self, child_type: NodeType, child_layer: int) -> str:
        """Build user prompt using template engine."""
        try:
            return build_prompt(
                "node_generation_user.txt.jinja",
                min_children=settings.min_children_per_node,
                max_children=settings.max_children_per_node,
                parent_title=self.node.title,
                parent_description=self.node.description,
                parent_type=self.node.type.value,
                parent_layer=self.node.layer,
                child_type=child_type.value,
                child_layer=child_layer,
                problem_statement=self.context.problem_statement,
                strategic_paths=self.context.strategic_paths,
                organizational_goals=self.context.organizational_goals,
                activity_insights=self.context.activity_insights,
                past_decisions=getattr(self.context, "past_decisions", []),
                relevant_content=getattr(self.context, "relevant_content", []),
            )
        except Exception as e:
            logger.error(f"Error building user prompt: {e}")
            # Fallback to simple prompt
            return self._build_fallback_user_prompt(child_type, child_layer)

    def _get_dag_context(self) -> str:
        """Get relevant DAG context for generation."""
        if not self.context.dag_state:
            return ""

        context_parts = []
        if "total_nodes" in self.context.dag_state:
            context_parts.append(f"Current DAG has {self.context.dag_state['total_nodes']} nodes")
        if "current_layer" in self.context.dag_state:
            context_parts.append(f"Building layer {self.context.dag_state['current_layer']}")

        return ". ".join(context_parts)

    def _get_sibling_context(self) -> List[dict]:
        """Get sibling node context if available."""
        # For now, return empty list - this could be enhanced with actual sibling data
        return []

    def _get_strategic_context(self) -> str:
        """Get strategic context from the strategic paths."""
        if not self.context.strategic_paths:
            return ""

        context_parts = []
        for path in self.context.strategic_paths[:3]:  # Limit to first 3 paths
            context_parts.append(f"Strategic Path: {path.title} - {path.description}")

        return "\n".join(context_parts)

    def _validate_children(self, children: List[DecisionNode]) -> List[DecisionNode]:
        """Validate and filter generated children."""
        validated = []

        for child in children:
            # Basic validation
            if not child.title.strip():
                logger.warning("Skipping child with empty title")
                continue

            if not child.description.strip():
                logger.warning(f"Skipping child with empty description: {child.title}")
                continue

            # Check title length
            if len(child.title) > 200:
                child.title = child.title[:197] + "..."
                logger.warning(f"Truncated long title for child: {child.title}")

            # Check description length
            if len(child.description) > 1000:
                child.description = child.description[:997] + "..."
                logger.warning(f"Truncated long description for child: {child.title}")

            validated.append(child)

        # Ensure we have minimum children
        if len(validated) < settings.min_children_per_node:
            logger.warning(f"Generated only {len(validated)} children, minimum is {settings.min_children_per_node}")

        # Limit to maximum children
        if len(validated) > settings.max_children_per_node:
            validated = validated[: settings.max_children_per_node]
            logger.warning(f"Limited children to maximum of {settings.max_children_per_node}")

        return validated

    def _build_fallback_system_prompt(self, child_type: NodeType, child_layer: int) -> str:
        """Build simple fallback system prompt."""
        return f"""You are a strategic planning expert. Generate {settings.min_children_per_node} to {settings.max_children_per_node} child nodes of type '{child_type.value}' for layer {child_layer}.

Parent node: {self.node.title} - {self.node.description}
Problem statement: {self.context.problem_statement}

Generate children that logically follow from the parent node and help address the problem statement."""

    def _build_fallback_user_prompt(self, child_type: NodeType, child_layer: int) -> str:
        """Build simple fallback user prompt."""
        return f"""Generate {settings.min_children_per_node} to {settings.max_children_per_node} high-quality child nodes of type '{child_type.value}' that logically follow from:

Parent: {self.node.title}
Description: {self.node.description}

Each child should have a clear title and detailed description."""
