"""Research-question prompts evaluated by the parity pipeline.

Two-level structure matching the deep research pipeline:
- Each prompt is a user-level research question (the "topic" for extraction).
- Each query is a keyword-based sub-query generated by the planner with
  search_terms (for DB search) and goals (the "directions" for extraction).

`ITERATION_PROMPTS` were the original 5 prompts used to iterate v4 → v6.1 of
the Gemma extraction prompt (and as the basis for the few-shots in v5+). They
are kept for reproducibility but NOT used for the headline evaluation
post-2026-05-27. Originally sourced from sonnet_results.json on the
gemma-in-deep-research branch.

`HOLDOUT_PROMPTS` are the 8 held-out research prompts used for the
leakage-corrected headline evaluation post-2026-05-27 (sourced from an internal
human-eval question library, items 1, 2, 5, 6, 7, 9, 11, 13; that library is not
included in this repository). The keyword queries were generated by running each prompt through
the production Deep Research feature in dev (after reseeding the dev DB with
the 12K+ research-export corpus via `make research_load`) and pulling the
planner-generated queries from the dev DB (research / researchquery tables).

Sanitised for publication
-------------------------
These prompts and planner directions were generated against a real corpus, so
they named real people and real companies. For the public version:

- Employees are referred to by role ("the CEO", "the research lead", "the design
  engineer", "the summer intern", "a research colleague") instead of by name,
  and gendered pronouns were changed to they/them so the placeholders do not
  re-identify anyone.
- Named prospects, their individual contacts, third-party vendors, and specific
  event names were removed. Where a prospect name was carrying the meaning of a
  sentence (for example an objection attributed to a specific account), it was
  replaced by the objection *category* and the substitution is noted inline.
- External academic collaborators are referred to generically.

The prompt and query structure is unchanged, so the pipeline still runs. The
retrieved corpus is not included in this repository, so the extraction results
are not reproducible from here.
"""

ITERATION_PROMPTS = [
    {
        "id": "q3_software_capitalization",
        "topic": (
            "I'm writing a software capitalization analysis for our financial audit. I need to determine our major "
            "phases of development in 2025. Can you propose 2-4 developmental phases we were in with our product last "
            "year? These should be extremely broad (i.e. application development phase), and with the audience of an "
            "accounting memo."
        ),
        "queries": [
            {
                "id": "q3_0",
                "title": "2025 product development phases and roadmap",
                "search_terms": "product development phases roadmap",
                "goals": (
                    "The goal is to identify the major developmental phases Convictional went through in 2025 for "
                    "software capitalization analysis. Look for engineering milestones, product releases, and strategic "
                    "shifts that would define broad development phases."
                ),
            },
            {
                "id": "q3_1",
                "title": "Engineering milestones and releases in 2025",
                "search_terms": "engineering milestones releases shipped",
                "goals": (
                    "The goal is to find concrete engineering milestones, product releases, and shipped features from "
                    "2025 to help define development phases for a software capitalization analysis."
                ),
            },
            {
                "id": "q3_2",
                "title": "2025 strategic pivots and company direction",
                "search_terms": "strategic pivot company direction goals",
                "goals": (
                    "The goal is to understand any strategic shifts, pivots, or major changes in company direction "
                    "during 2025 that would indicate transitions between development phases."
                ),
            },
            {
                "id": "q3_3",
                "title": "Q2 2025 technical architecture and feature development",
                "search_terms": "Q2 technical architecture features",
                "goals": (
                    "The goal is to identify specific engineering activities, architectural decisions, and feature "
                    "development work that occurred in Q2 2025."
                ),
            },
            {
                "id": "q3_4",
                "title": "2025 infrastructure architecture technical platform",
                "search_terms": "infrastructure architecture platform",
                "goals": (
                    "The goal is to understand the technical infrastructure and platform architecture development "
                    "throughout 2025 to help categorize development phases."
                ),
            },
            {
                "id": "q3_5",
                "title": "Q3 and Q4 2025 feature deliveries and product milestones",
                "search_terms": "Q3 Q4 features shipped delivered",
                "goals": (
                    "The goal is to identify specific features, capabilities, and product milestones delivered in "
                    "Q3 and Q4 of 2025 to complete the picture of development phases."
                ),
            },
        ],
    },
    {
        "id": "q4_icp_decision_history",
        "topic": (
            "How did we decide on the current ICP? Can you point me to the decisions and discussions we had "
            "surrounding the ICP? I'm especially curious on any tradeoffs we made, and the why behind our decision."
        ),
        "queries": [
            {
                "id": "q4_0",
                "title": "ICP decision-making and strategy",
                "search_terms": "ICP decision target customer",
                "goals": (
                    "The goal is to find the core decisions and discussions that led to Convictional's current Ideal "
                    "Customer Profile (ICP), including tradeoffs and the reasoning behind the decision."
                ),
            },
            {
                "id": "q4_1",
                "title": "ICP tradeoffs and constraints",
                "search_terms": "ICP tradeoffs constraints criteria",
                "goals": (
                    "This query aims to uncover explicit discussions about tradeoffs made when defining the ICP. "
                    "Focus on understanding what was deprioritized and why."
                ),
            },
            {
                "id": "q4_2",
                "title": "Target market and customer profile discussions",
                "search_terms": "target market customer profile remote 50-200",
                "goals": (
                    "This query is designed to capture broader discussions about target market selection and customer "
                    "profiling that informed the ICP definition."
                ),
            },
            {
                "id": "q4_3",
                "title": "ICP evolution from enterprise to SMB",
                "search_terms": "100+ person pivot downmarket",
                "goals": (
                    "The goal is to understand the strategic pivot from targeting 100+ person organizations to "
                    "including smaller companies, and the reasoning behind it."
                ),
            },
            {
                "id": "q4_4",
                "title": "ICP market size addressable market tradeoffs",
                "search_terms": "addressable market TAM narrow ICP",
                "goals": (
                    "This query aims to find discussions about the market sizing implications and addressable market "
                    "tradeoffs when the team narrowed or expanded the ICP."
                ),
            },
            {
                "id": "q4_5",
                "title": "ICP definition evolution and rationale",
                "search_terms": '"ideal customer profile" definition attributes criteria',
                "goals": (
                    "The goal is to find documents detailing the origin and evolution of Convictional's ICP "
                    "definition, including the specific attributes and criteria used."
                ),
            },
        ],
    },
    {
        "id": "q8_product_launches",
        "topic": (
            "I want to know more about the product launches Convictional has had over the past 2 years. For each one, "
            "I want to know what products we launched, what was the company activity surrounding the launch, and what "
            "was the date/time period of the launch."
        ),
        "queries": [
            {
                "id": "q8_0",
                "title": "Convictional product launches (2024-2026)",
                "search_terms": "product launch",
                "goals": (
                    "The goal is to identify all product launches Convictional has had over the past 2 years, "
                    "including what was launched, the surrounding activity, and the timeline."
                ),
            },
            {
                "id": "q8_1",
                "title": "Product announcements and releases",
                "search_terms": "announcement release shipped",
                "goals": (
                    "The goal is to capture company communications and activities around product releases that may "
                    "not be explicitly labeled as launches."
                ),
            },
            {
                "id": "q8_2",
                "title": "Roadmap execution and feature delivery",
                "search_terms": "roadmap shipped features",
                "goals": (
                    "The goal is to understand Convictional's roadmap execution over the past 2 years to identify "
                    "what products and features were delivered."
                ),
            },
            {
                "id": "q8_3",
                "title": "Posts feature development timeline and stabilization",
                "search_terms": '"Posts" feature bugs shipped',
                "goals": (
                    "The goal is to understand the complete development arc of the Posts feature from initial "
                    "conception through stabilization."
                ),
            },
            {
                "id": "q8_4",
                "title": "Winter 2025 launch features and positioning",
                "search_terms": '"Winter Launch" January 2025 features capabilities',
                "goals": (
                    "The goal is to deeply investigate the Winter 2025 launch to understand what specific product "
                    "features and capabilities were included."
                ),
            },
            {
                "id": "q8_5",
                "title": "October 2025 launch event and release details",
                "search_terms": "October 2025 launch release shipped",
                "goals": (
                    "The goal is to identify specific product features, capabilities, and positioning included in "
                    "Convictional's October 2025 launch."
                ),
            },
        ],
    },
    {
        "id": "q10_work_alignment",
        "topic": (
            "How well has work across the company within the last few weeks aligned to the goals of the organization? "
            "Anything we should spend more or less time on?"
        ),
        "queries": [
            {
                "id": "q10_0",
                "title": "Recent work on financial sustainability and GTM execution",
                "search_terms": "revenue GTM deals sales financial",
                "goals": (
                    "The goal is to understand how much recent work has focused on the Financial Sustainability "
                    "goals, including executing the GTM motion and revenue generation."
                ),
            },
            {
                "id": "q10_1",
                "title": "Recent work on thought leadership and research outputs",
                "search_terms": "research essays speaking events book proposal goal alignment evaluation",
                "goals": (
                    "The goal is to evaluate how much effort has been invested in the Alignment Moonshot goals "
                    "related to thought leadership and research outputs."
                ),
            },
            {
                "id": "q10_2",
                "title": "Recent work on Slack migration and replacement goals",
                "search_terms": "Slack migration replacement",
                "goals": (
                    "The goal is to assess how much recent work has been directed toward the Slack-related goals, "
                    "which are central to the company's product strategy."
                ),
            },
            {
                "id": "q10_3",
                "title": "AI tool costs and adoption",
                "search_terms": "AI costs Anthropic Gemini Claude spending budget",
                "goals": (
                    "The goal is to understand the company's AI tool spending, adoption patterns, and cost management "
                    "in the last few weeks."
                ),
            },
            {
                "id": "q10_4",
                "title": "Q2 roadmap progress and blockers",
                "search_terms": "Q2 roadmap blockers",
                "goals": (
                    "The goal is to assess progress on the Q2 roadmap, which is critical to the broader Slack "
                    "migration objective."
                ),
            },
            {
                "id": "q10_5",
                "title": "Q2 roadmap progress and feature tracking",
                "search_terms": "Q2 roadmap features shipped",
                "goals": (
                    "The goal is to assess progress on the Slack Migration objective to ship the Q2 roadmap by "
                    "examining what features have been delivered."
                ),
            },
        ],
    },
    {
        "id": "q12_recent_product_work",
        "topic": "Give me an update about recent product work and activity around the company within the last week.",
        "queries": [
            {
                "id": "q12_0",
                "title": "Recent product work and development",
                "search_terms": "product development roadmap features",
                "goals": (
                    "The goal is to surface recent product work, feature development, and engineering activities "
                    "from the last week."
                ),
            },
            {
                "id": "q12_1",
                "title": "Customer and deal progress",
                "search_terms": "customer deals pipeline revenue",
                "goals": (
                    "The goal is to track customer-facing activities, deal progression, and revenue-related "
                    "developments from the last week."
                ),
            },
            {
                "id": "q12_2",
                "title": "Company activity and team updates",
                "search_terms": "updates activity decisions team",
                "goals": (
                    "The goal is to capture general company activity, team communications, and organizational "
                    "updates from the past week."
                ),
            },
            {
                "id": "q12_3",
                "title": "Workspace migration PR status and merge timeline",
                "search_terms": "workspace migration PR merge",
                "goals": (
                    "The goal is to answer the specific follow-up question about the current status of workspace "
                    "migration PRs and their expected merge timeline."
                ),
            },
            {
                "id": "q12_4",
                "title": "Q2 roadmap priorities and timeline",
                "search_terms": '"Q2 roadmap" priorities timeline',
                "goals": (
                    "The goal is to understand the current status and timeline for the Q2 roadmap mentioned in "
                    "the Slack Migration goal."
                ),
            },
            {
                "id": "q12_5",
                "title": "TurboQuant production deployment and chat workspace PRs",
                "search_terms": '"TurboQuant" production deployment "PR 4" "PR 5" workspace',
                "goals": (
                    "The goal is to determine whether the TurboQuant compression experiment was deployed to "
                    "production and the status of workspace-related PRs."
                ),
            },
        ],
    },
]


HOLDOUT_PROMPTS = [
    {
        "id": 'q1_analytics_principles',
        "topic": (
            "What's the history of our analytics principles at Convictional? Everything that a new senior analytics "
            'engineer would need to get up to speed.'
        ),
        "queries": [
            {
                "id": 'q1_0',
                "title": 'Analytics architecture and data modeling decisions',
                "search_terms": 'analytics data modeling',
                "goals": (
                    "Surface the historical architectural and data modeling decisions that underpin Convictional's "
                    'analytics stack. A senior analytics engineer needs to understand not just the current state but how '
                    'the architecture evolved — what was tried, what was abandoned, and why. Once findings are gathered, '
                    'investigate specific tooling choices (e.g. dbt, warehouse selection, metric layers), any migrations '
                    'or refactors, and the reasoning documented at the time. Additional directions: look for ADRs '
                    '(architecture decision records), RFCs, or retrospectives related to analytics infrastructure.'
                ),
            },
            {
                "id": 'q1_1',
                "title": 'Analytics principles and philosophy at Convictional',
                "search_terms": 'analytics principles',
                "goals": (
                    'Uncover the foundational analytics principles, philosophies, and guidelines that have been '
                    'established at Convictional over time. This is the core of what a new senior analytics engineer needs '
                    "to understand — the 'why' behind how Convictional approaches data and analytics. Once found, look "
                    "deeper into who authored these principles, when they were established, and whether they've evolved. "
                    'Additional directions: trace any debates or revisions to the principles, identify key decision-makers '
                    'who shaped them, and look for any tensions between the original principles and current practice.'
                ),
            },
            {
                "id": 'q1_2',
                "title": 'Analytics onboarding and standards documentation',
                "search_terms": 'analytics standards onboarding',
                "goals": (
                    'Find any onboarding documentation, style guides, contribution standards, or runbooks created for '
                    'analytics work at Convictional. This helps a new senior hire understand the expected norms, '
                    'conventions, and workflows on the team. Once found, assess how comprehensive the documentation is and '
                    'identify gaps. Additional directions: look for references to naming conventions, testing '
                    'expectations, documentation requirements, and peer review processes for analytics work — these are '
                    'often where institutional knowledge lives.'
                ),
            },
            {
                "id": 'q1_3',
                "title": 'a third-party analytics vendor deprecation and removed dbt models',
                "search_terms": '"a third-party analytics vendor" dbt removed deprecated',
                "goals": (
                    'Identify exactly which a third-party analytics vendor dbt models and semantic layer metrics were removed in August 2025 '
                    '(PR #1057), and understand the product context that drove the deprecation decision. Prior research '
                    'confirms the removal happened and that the analytics lead confirmed old a third-party analytics vendor data was no longer '
                    'queryable post-merge, but the specific model names, metric names, and the business rationale for '
                    'sunsetting a third-party analytics vendor as a product area have not yet been surfaced. Once found, cross-reference '
                    'against the broader pipeline model inventory to understand what gaps the removal created and whether '
                    'any downstream canvases or metrics were affected. Additional research directions: determine what '
                    'a third-party analytics vendor was as a product concept, who made the decision to deprecate it, and whether there are any '
                    'references to a third-party analytics vendor in current documentation that should be cleaned up.'
                ),
            },
            {
                "id": 'q1_4',
                "title": 'dbt CI/CD and environment promotion practices',
                "search_terms": 'dbt environment promotion CI/CD',
                "goals": (
                    'The goal is to surface documentation, decisions, or discussions around how dbt model changes are '
                    'tested and promoted through dev, staging, and production environments at Convictional. Prior research '
                    'has established the existence of a convictional/data GitHub repo and a pattern of PR-driven modelling '
                    'changes, but the CI/CD pipeline and environment structure have not yet been explicitly documented. '
                    'Once findings are gathered, investigate: what branch/environment conventions exist in the dbt '
                    'project, whether there are automated tests (dbt test, Great Expectations, or similar) run on PR, how '
                    'dbt Cloud jobs are structured per environment, and whether there are any documented policies around '
                    'breaking changes to semantic layer metrics. Additional research directions: look for any documented '
                    'rollback procedures, environment-specific BigQuery datasets, and whether schema tests or source '
                    'freshness checks are part of the standard PR review process.'
                ),
            },
            {
                "id": 'q1_5',
                "title": 'Analytics conversion funnel dbt schema and lineage',
                "search_terms": 'conversion funnel dbt model',
                "goals": (
                    'The goal is to uncover the full schema and data lineage of the GTM conversion funnel model in dbt — '
                    'specifically all upstream source tables feeding into it, the exact SQL definitions for each funnel '
                    'stage, and any intermediate models in between. Previous learnings confirmed that gmail account '
                    'connection uses `created_at` from the `gmailaccount` table and onboarding completion uses '
                    '`onboarding_completed_at` from the `user` model, but the complete funnel definition (all stages, '
                    'their timestamps/event triggers, and the mart model structure) has not yet been fully documented. '
                    'Once found, cross-reference with the semantic layer to see which funnel metrics are exposed for '
                    'querying in Analysis Threads. Additional directions: look for any recent PRs in the convictional/data '
                    "repo that touched the conversion funnel model, check whether 'weekly active teams' is defined as a "
                    'funnel stage or a separate adoption metric, and identify if there are any known data quality issues '
                    'or filters applied at the staging layer that affect funnel counts.'
                ),
            },
        ],
    },
    {
        "id": 'q2_design_principles',
        "topic": (
            "What's the history of our design principles at Convictional? Specifically looking for the original principles "
            'for 2024 relating to the decide project and in the time since. Everything that a new senior design engineer '
            'would need to get up to speed.'
        ),
        "queries": [
            {
                "id": 'q2_0',
                "title": 'Decide project design principles 2024',
                "search_terms": '"decide" design principles',
                "goals": (
                    'Uncover the original design principles established for the Decide project in 2024. This is the '
                    'foundational document a new senior design engineer would need to understand the genesis of '
                    "Convictional's design philosophy. Once found, look for the authors, the context in which they were "
                    'written, and any explicit rationale given for each principle. Additional directions: cross-reference '
                    'these principles against any product philosophy documentation to understand how they connect to the '
                    'broader decision context problem mission.'
                ),
            },
            {
                "id": 'q2_1',
                "title": 'Design principles evolution post-2024',
                "search_terms": 'design principles guidelines',
                "goals": (
                    "Identify how Convictional's design principles have evolved since the original Decide project "
                    'principles were established in 2024. A new senior design engineer needs to understand not just the '
                    'starting point but the full arc of design thinking at the company. Look for any revisions, additions, '
                    'deprecations, or debates around design principles. Additional directions: pay attention to any '
                    'principles that were introduced in response to specific product decisions or customer feedback, and '
                    'whether the Slack disruption pivot affected design philosophy.'
                ),
            },
            {
                "id": 'q2_2',
                "title": 'UI/UX design decisions and rationale',
                "search_terms": 'design decisions UI',
                "goals": (
                    'Surface documented design decisions, rationale, and discussions that reflect applied design '
                    'principles at Convictional over time. While the other queries target explicit principle documents, '
                    'this query targets the practical application — helping a new senior design engineer understand how '
                    'principles translate into real product choices. Additional directions: look for recurring themes or '
                    'tensions in design decisions that might indicate implicit principles not formally documented, and any '
                    "design reviews or critiques that reveal the team's design standards."
                ),
            },
            {
                "id": 'q2_3',
                "title": 'Amish Mode design process origin',
                "search_terms": '"Amish Mode" design',
                "goals": (
                    "Identify what 'Amish Mode' is as a named design methodology at Convictional — who coined it, what it "
                    'means in practice (e.g., stripped-down, low-fidelity, constraint-based design), and whether it has '
                    "been formalized beyond Riishi Jeevakumar's usage. Previous research surfaced that Riishi used the "
                    'term for an early, stripped-down design process on Goals Merchandising, but the origin and scope are '
                    'unknown. Once found, a new senior design engineer would need to understand whether this is a broadly '
                    'applied process norm, how it relates to other design phases (e.g., when to use it vs. higher-fidelity '
                    'iteration with Claude Design), and who to consult for guidance on applying it.'
                ),
            },
            {
                "id": 'q2_4',
                "title": 'Information architecture and navigation structure evolution',
                "search_terms": 'navigation sidebar routing goals decisions',
                "goals": (
                    "Surface documented decisions about the app's information architecture (IA) and navigation structure — "
                    'specifically how the sidebar, routing, and the relationship between goals, decisions, and chats have '
                    'been structured and evolved visually from 2024 to the present. This directly addresses one of the '
                    'three open follow-up questions: whether there is a documented evolution of IA or nav structure. Once '
                    'results are found, look for any explicit rationale about why certain items are grouped or ordered the '
                    'way they are, whether there were debates about top-level nav items, and how the introduction of new '
                    'features (e.g., Decision Process, chat index, tasks/glue) affected the overall IA. Additional '
                    'directions: check for any Figma file references, routing PRs with design commentary, or posts where '
                    'the design engineer or the CEO weigh in on structural navigation decisions.'
                ),
            },
            {
                "id": 'q2_5',
                "title": 'the design engineer design principles documentation',
                "search_terms": '"the design engineer" design principles system',
                "goals": (
                    'Uncover any formal or informal design principles, guidelines, or documented design philosophy '
                    "authored or attributed to Convictional's primary design engineer. Previous "
                    'research has established the design engineer as the authoritative design voice, and that no explicit 2024 '
                    "principles document for the 'decide' project has been surfaced yet. The goal is to find the canonical "
                    'or closest-to-canonical artifact that a new senior design engineer would use as their primary '
                    'reference. Once found, extract each principle, its rationale, and any connection to the decision '
                    'context problem mission. Additional research directions: cross-reference findings against the Ben '
                    'Lidgard Figma system baseline to understand what was inherited vs. invented post-pivot; check whether '
                    'any principles were documented in the context of the July–September 2024 rebrand evaluation or the '
                    'December 2024 Bart De Langhe advisor meeting, both of which surfaced concrete design feedback; and '
                    "look for any connection between the design engineer's principles and the anti-distraction / zen-mode stance "
                    'documented in April 2026.'
                ),
            },
        ],
    },
    {
        "id": 'q5_bio_recommendations',
        "topic": (
            'Can you recommend updates I can make to my bio in the app based on things I actually work on, make decisions '
            'about, and the nature of my work based on the context you have?'
        ),
        "queries": [
            {
                "id": 'q5_0',
                "title": "the research lead's research decisions and priorities",
                "search_terms": '"the research lead" research decisions',
                "goals": (
                    'Find internal records of decisions the research lead has made or been involved in, particularly around research '
                    'direction, ML architecture, and experiment design. This will help identify what they actually work on '
                    "day-to-day versus what's in their bio. Look for decision documents, meeting notes, or any artifacts "
                    'that show their sphere of influence. Further research could explore specific projects or initiatives '
                    "they have led."
                ),
            },
            {
                "id": 'q5_1',
                "title": "the research lead's experiments and prototypes",
                "search_terms": '"the research lead" experiments prototypes',
                "goals": (
                    'Surface any experiment logs, prototype descriptions, or research artifacts associated with the research lead. This '
                    'helps identify the concrete technical work they do — LLM evaluation, information retrieval, NLP — so '
                    'the bio can reflect actual recent work rather than generic descriptions. Follow-up could include '
                    "looking at specific research areas like 'goal alignment evaluation set' which is an org-level goal they "
                    'may be contributing to.'
                ),
            },
            {
                "id": 'q5_2',
                "title": 'the research lead ML research contributions',
                "search_terms": '"the research lead" ML research',
                "goals": (
                    "Identify the research lead's specific contributions to ML and AI research within Convictional, including any "
                    'academic output, evaluation sets, or thought leadership pieces. This will inform bio updates that '
                    "accurately reflect their technical focus areas. Could also look at their involvement in the 'official "
                    "goal alignment evaluation set' goal and the Alignment Moonshot initiatives."
                ),
            },
            {
                "id": 'q5_3',
                "title": "the research lead's formal goal ownership and research bets",
                "search_terms": '"the research lead" goals ownership bets',
                "goals": (
                    'The goal is to surface any formal goals, subgoals, or bets that the research lead has explicit ownership or '
                    "accountability for in the app — beyond the already-identified 'AI Moat' goal. This will help "
                    'articulate their influence sphere more precisely in an updated bio, distinguishing between advisory '
                    'roles and formal decision ownership. Follow-up directions: Cross-reference any owned goals with '
                    'active experiments (AlignSim, deep research pipeline, Goal Alignment eval) to see if there are more '
                    'recent or additional goal structures tied to their work; also check if any goals relate to the '
                    "org-level 'Build the official goal alignment evaluation set' objective, which the research lead may be a primary "
                    'contributor to.'
                ),
            },
            {
                "id": 'q5_4',
                "title": "the research lead's AlignSim and academic collaboration outputs",
                "search_terms": '"the research lead" academic publication collaboration',
                "goals": (
                    "The goal is to find any recent records of the research lead's academic collaboration with an external academic collaborator and the "
                    'AlignSim benchmark — specifically any co-authored drafts, shared experiment designs, or publication '
                    'plans that could be cited in an updated bio. Prior research confirmed the collaboration exists but '
                    "didn't surface concrete deliverables or timelines. Once found, this will help determine whether the "
                    'bio should reference AlignSim as a shipped benchmark, a work-in-progress, or an upcoming publication. '
                    'Additional directions: look for any internal write-ups or goal tracking entries that describe the '
                    'intended venue (conference, journal, blog) for AlignSim results; check whether the goal alignment '
                    'eval set (listed as a company goal) is formally linked to AlignSim or is a separate artifact.'
                ),
            },
            {
                "id": 'q5_5',
                "title": 'the research lead AlignSim goal alignment benchmark',
                "search_terms": '"AlignSim" goal alignment benchmark',
                "goals": (
                    'The goal of this query is to surface any internal documentation, posts, or discussions specifically '
                    "about AlignSim and the goal alignment evaluation set — to determine whether the research lead's bio should "
                    'explicitly name AlignSim as a flagship research contribution, and to understand how it connects to '
                    "the Alignment Moonshot initiative (specifically the 'Build the official goal alignment evaluation "
                    "set' subgoal). Once results are found, the next step is to assess how mature and public-facing "
                    'AlignSim is (e.g., is it referenced in external essays, proposals, or speaking materials?) and '
                    "whether it's appropriate to name it in a standing professional bio. Additional research directions: "
                    'Does AlignSim appear in any book proposal or publisher-facing materials, which would confirm its role '
                    'as a thought leadership anchor? Has the research lead published any external write-up or essay about AlignSim that '
                    'could serve as a citation in their updated bio?'
                ),
            },
        ],
    },
    {
        "id": 'q6_research_function_principles',
        "topic": (
            "What's the history of our research function principles at Convictional? Specifically looking for the original "
            'principles for 2024 relating to the decide project and in the time since. Everything that a new research team '
            'member would need to get up to speed.'
        ),
        "queries": [
            {
                "id": 'q6_0',
                "title": 'Research function principles 2024 - Decide project',
                "search_terms": 'research principles "decide"',
                "goals": (
                    "Find the original research function principles from 2024 that were tied to the 'decide' project at "
                    'Convictional. This will establish the foundational baseline for understanding how the research '
                    'function was initially structured. Once found, look for any documents, memos, or discussions that '
                    'articulate the rationale behind each principle, who authored them, and how they were intended to '
                    'guide research work on the decide project specifically.'
                ),
            },
            {
                "id": 'q6_1',
                "title": 'Research principles evolution and updates',
                "search_terms": 'research principles guidelines',
                "goals": (
                    'Discover how the research function principles at Convictional have evolved since 2024, including any '
                    'revisions, additions, or formal updates. This is critical for a new team member to understand the '
                    'current state. Look for any retrospectives, principle revisions, onboarding documents, or research '
                    'strategy discussions that show how thinking has matured — especially in relation to LLM evaluation, '
                    'information retrieval, and the decision context problem.'
                ),
            },
            {
                "id": 'q6_2',
                "title": 'Research team onboarding and direction',
                "search_terms": 'research onboarding direction',
                "goals": (
                    'Surface any onboarding materials, research direction documents, or team norms specifically written '
                    'for or about the research function at Convictional. The goal is to identify everything a new research '
                    'team member would need to get up to speed — including role expectations, experimental design '
                    'standards, academic output norms, and how research priorities are set. Additional directions: look '
                    "for any documents referencing the research lead's research priorities or guidance notes shared with new "
                    'collaborators.'
                ),
            },
            {
                "id": 'q6_3',
                "title": 'Decision extraction research prior work',
                "search_terms": 'decision extraction research',
                "goals": (
                    'Surface any prior research reports, experiment logs, or documented findings from the original '
                    'decision extraction research work referenced by a research colleague in November 2025 as needing to be '
                    "'dusted off.' The goal is to identify whether a formal research report or experiment log exists from "
                    "this earlier work — likely predating the October 2025 'Next Research Focus' post — and whether it "
                    'contains methodology, findings, or evaluation results that would inform a new research team member '
                    "about the historical foundations of the team's approach to decisions as proxies for revealed goals. "
                    "If found, follow up by checking whether this work was connected to the 2024 'decide' project period, "
                    'and whether it contains any principles, constraints, or lessons that were carried forward into the '
                    'current research direction.'
                ),
            },
            {
                "id": 'q6_4',
                "title": "Research function principles 'decide' project history",
                "search_terms": 'research principles "decide" "Context Graph" WAT WDT evolution',
                "goals": (
                    'The goal is to surface any documented or discussed research function principles, charters, or guiding '
                    "frameworks that were tied to the 'decide' project in 2024, and to trace how those principles evolved "
                    'through the Slack disruption pivot and into 2025–2026. Previous queries have confirmed that no formal '
                    "'Research Principles' document has been indexed, so this query should probe adjacent artifacts — "
                    'mentions of principles in decision threads, onboarding docs, or strategic planning posts — that '
                    'collectively reconstruct the foundational research philosophy. Once results are found, look for: (1) '
                    'who authored or shaped the principles (the CEO, the research lead, a research colleague), (2) how WAT/WDT metrics were defined and '
                    'later replaced or translated, (3) how the Context Graph research bets were framed and what failed '
                    'experiments were documented, and (4) what the current state of the goal alignment evaluation set '
                    "methodology is. Additional directions: cross-reference the 'Business Entity Entropy' paper context "
                    'against any internal framing of the high-entropy search problem to see if the research team '
                    'explicitly connected external literature to internal principles; look for any post by the CEO '
                    "proposing the 'ten things that influence high entropy query performance' manifesto, as this may be "
                    'the closest thing to a formal research principles document produced in late 2025.'
                ),
            },
            {
                "id": 'q6_5',
                "title": 'Context Compression RFC embedder fine-tuning eval results',
                "search_terms": 'embedder fine-tuning eval results',
                "goals": (
                    'The goal is to surface the current status of the embedder fine-tuning research bet — one of the two '
                    'original bets from the Context Compression RFC (Nov 25, 2025). Specifically, we want to find any eval '
                    'results comparing fine-tuned open-source embedding models against OpenAI embeddings, any experiment '
                    'reports or human eval outcomes tied to this bet, and any decisions made about whether to continue, '
                    'pause, or pivot the fine-tuning direction. Once found, follow-up directions should include: (1) '
                    'cross-referencing findings against the Topics & Communities (GraphRAG) bet to understand relative '
                    'progress; (2) checking whether the embedder fine-tuning work fed into the post-March 2026 eval '
                    'methodology evolution (novel cases, inter-rater agreement fixes); and (3) looking for any '
                    'auto-researcher daily reports that surfaced relevant embedding fine-tuning literature from cs.AI or '
                    'cs.IR that may have influenced the research direction.'
                ),
            },
        ],
    },
    {
        "id": 'q7_intern_summer',
        "topic": 'What did the summer intern work on summer 2025?',
        "queries": [
            {
                "id": 'q7_0',
                "title": "the summer intern's projects and work",
                "search_terms": '"the summer intern" projects work',
                "goals": (
                    'Find out what the summer intern was working on during summer 2025. Look for any documents, updates, or '
                    'activity attributed to them during that period. If results are found, follow up by exploring specific '
                    'projects or initiatives they were involved in to get a fuller picture of their contributions.'
                ),
            },
            {
                "id": 'q7_1',
                "title": "the summer intern's updates and contributions",
                "search_terms": '"the summer intern"',
                "goals": (
                    'Broadly surface any internal content mentioning the summer intern during summer 2025, including updates, '
                    'goals, decisions, or messages. This casts a wide net to catch anything that narrower queries might '
                    'miss. Further research should focus on the specific projects or teams mentioned in the results.'
                ),
            },
            {
                "id": 'q7_2',
                "title": 'ColBERT dimensionality analysis results',
                "search_terms": 'ColBERT dimensionality analysis results',
                "goals": (
                    'The goal is to find whether the summer intern completed the dimensionality analysis they mentioned wanting to run, '
                    'and whether the results are documented internally — in a GDrive folder, a PR, or a shared update. '
                    "Prior research confirmed the summer intern hypothesised document length was a key factor in MUVERA's performance "
                    'collapse on business data, and validated it with synthetic experiments. This follow-up should surface '
                    'any final numbers, charts, or conclusions from that analysis, as well as any post-internship scoping '
                    'discussions around the database migration required for ColBERT (e.g., moving away from pgvector). '
                    'Additional research directions: check for any engineering tickets or discussions about the Stage 5 '
                    'migration plan; look for any handoff documents or final presentation artifacts that may contain the '
                    'full precision/recall/NDCG/MAP breakdown by dataset.'
                ),
            },
            {
                "id": 'q7_3',
                "title": 'the summer intern ColBERT dimensionality analysis findings',
                "search_terms": '"the summer intern" dimensionality analysis ColBERT',
                "goals": (
                    'The goal is to find whether the summer intern completed their planned dimensionality analysis before their last day '
                    '(August 26, 2025), and if so, what the findings were. This is a known open question from previous '
                    'research — their Stage 5 implementation research was contingent on team approval, and a dimensionality '
                    'analysis was referenced as a potential next step. Look for any documents, updates, PRs, or comments '
                    'from late August 2025 that capture these results. If found, follow up by exploring the specific '
                    'metrics (precision, recall, NDCG) for ColBERT vs. single-vector on the real business (seed) dataset, '
                    'and any concrete infrastructure or database migration recommendations they may have left behind for '
                    'implementing ColBERT at Convictional.'
                ),
            },
        ],
    },
    {
        "id": 'q9_research_posts',
        "topic": (
            "There's been a number of posts for the research group sharing papers touching on different techniques or "
            'experiments we might be interested. I want a report comparing what has been shared, and want to prioritize '
            'the report by expected impact and experiment effort trade-offs.'
        ),
        "queries": [
            {
                "id": 'q9_0',
                "title": 'Research group paper shares',
                "search_terms": 'research papers shared',
                "goals": (
                    'Find all posts and shares from the research group where papers, techniques, or experiments were '
                    'shared internally. The goal is to compile a comprehensive list of the papers and topics that have '
                    'been circulated, so they can be compared and prioritized by impact vs. effort. Once results are '
                    'found, look for recurring themes, methodologies, or experimental directions that appear across '
                    'multiple shares to identify clustering patterns.'
                ),
            },
            {
                "id": 'q9_1',
                "title": 'ML/AI techniques and experiments discussed',
                "search_terms": 'experiment technique LLM',
                "goals": (
                    'Surface internal discussions around specific ML/AI techniques, experiments, or evaluation methods '
                    'that have been proposed or highlighted in the research group. The goal is to understand which '
                    'experiments or techniques were discussed in enough detail to assess implementation effort. Further '
                    'research should explore any notes on feasibility, complexity estimates, or prior attempts at similar '
                    'experiments within Convictional.'
                ),
            },
            {
                "id": 'q9_2',
                "title": 'Research priorities and impact assessments',
                "search_terms": 'research priority impact',
                "goals": (
                    'Identify any internal discussions or documents where research ideas were evaluated, ranked, or '
                    'assessed for impact — particularly in relation to the decision context problem or LLM evaluation '
                    'work. This will help anchor the impact side of the impact vs. effort trade-off matrix. Additional '
                    'research directions include looking for any OKR or goal alignment discussions that tie research '
                    "directions to Convictional's broader strategic goals."
                ),
            },
            {
                "id": 'q9_3',
                "title": 'Research group paper shares and experiment candidates',
                "search_terms": 'research group paper shared',
                "goals": (
                    'The goal is to surface any remaining internal posts from the research group where papers, techniques, '
                    'or experiments were shared that have not yet been captured by previous queries. Given the existing '
                    'learnings already cover RAPTOR, MultEval, Karpathy AutoResearch, and the auto-research ArXiv '
                    'pipeline, this query should help fill gaps — particularly around: (1) any additional papers shared '
                    'between March 2026 and now that the pipeline may have flagged as experiment-ready but were not acted '
                    'on; (2) any follow-up discussion threads on Leiden community summarization benchmarking or '
                    'faithfulness recall metrics; and (3) any inter-annotator agreement data or human eval rounds '
                    'connected to the LLM-as-a-Judge goal alignment evaluation set. Once results are found, '
                    'cross-reference against the known paper list (RAPTOR, MultEval 2604.26679v1, Karpathy AutoResearch) '
                    'to identify net-new entries, then cluster by methodology (retrieval/IR, evaluation/judging, agentic '
                    'pipelines) and score each cluster by estimated experiment effort vs. expected impact on '
                    "Convictional's core retrieval and evaluation infrastructure."
                ),
            },
            {
                "id": 'q9_4',
                "title": 'GraphRAG embedder fine-tuning context compression eval results',
                "search_terms": 'GraphRAG embedder fine-tuning compression eval',
                "goals": (
                    'Goal: Surface any documented evaluation results, benchmarks, or comparative findings across the three '
                    'main retrieval/compression research bets — Topics & Communities (GraphRAG/RAPTOR), embedder '
                    'fine-tuning, and JiT on-the-fly context compression — to populate the impact side of the impact vs. '
                    'effort trade-off matrix. This directly complements already-retrieved context on the architectural '
                    'regression (PR #3325) and the MultEval/subjectiveness findings.  Once results are found, advance the '
                    'research by: (1) mapping each paper or experiment to concrete effort estimates (e.g., infrastructure '
                    'requirements, compute cost, whether open-source LLM is needed) to avoid the known failure mode the research lead '
                    'flagged in March 2026 where recommendations were invalidated by infrastructure constraints; (2) '
                    "cross-referencing against the CEO's framing that all bets are sub-problems of 'solve "
                    "high-entropy research context search' — so prioritize techniques that generalize across query types; "
                    '(3) checking whether the RAPTOR summarization faithfulness benchmarking gap (noted Dec 2025) has been '
                    'closed, since that IR-layer eval is a prerequisite for valid end-to-end comparison; (4) identifying '
                    'whether the JiT compression experiments have been unblocked following the recursive tree regression '
                    'fix, or if that remains an open blocker.'
                ),
            },
            {
                "id": 'q9_5',
                "title": 'Goals alignment production route and judge prompt status',
                "search_terms": 'goals_alignment judge prompt rubric production',
                "goals": (
                    'Surface the current implementation status of the /goals_alignment production route, particularly '
                    'whether a calibrated judge prompt or rubric has been developed following the ICC human eval findings '
                    'and the MultEval paper (arxiv 2604.26679v1). Research should determine: (1) whether the collaborative '
                    'criteria-alignment approach from MultEval has been applied to synthesize the divergent ICC rater '
                    'judgements into a working judge prompt; (2) whether the domain-expert weighting proposal (the '
                    "CEO's 'believability scores' analogy) or the pin/dismiss-style learning loop for bootstrapping a "
                    'tuned LLM judge have moved beyond proposal stage; (3) the current production readiness of the '
                    '/goals_alignment route and any open blockers. Further research directions: trace any follow-up posts '
                    'or RFCs referencing the goal alignment evaluation set build-out, check whether the junk email ML '
                    'privacy policy conflict has been resolved and if that unblocking had any downstream effect on other '
                    'ML training decisions, and look for any experiments that extend LLM arithmetic or structured data '
                    'extraction into quantitative goal tracking or scenario planning use cases.'
                ),
            },
        ],
    },
    {
        "id": 'q11_recent_personal_work',
        "topic": (
            'What work have I done in the last week? I want to know about major things that relate to goals of the '
            'organization and moving those goals forward.'
        ),
        "queries": [
            {
                "id": 'q11_0',
                "title": "the research lead's recent research activity",
                "search_terms": '"the research lead" research',
                "goals": (
                    'Identify the major research work the research lead has done in the last week, including experiments, prototypes, '
                    'evaluations, or findings. Once results are found, look for connections to org goals like LLM '
                    'evaluation, goal alignment, or Slack disruption research. Additional directions: cross-reference any '
                    "outputs (papers, prototypes, eval sets) with the 'Alignment Moonshot' and 'Build the official goal "
                    "alignment evaluation set' goals."
                ),
            },
            {
                "id": 'q11_1',
                "title": 'Recent ML/AI evaluation experiments',
                "search_terms": 'LLM evaluation experiment',
                "goals": (
                    'Surface any recent experiment design or results the research lead has been involved in related to LLM evaluation, '
                    'information retrieval, or NLP work. This directly relates to the goal of building the official goal '
                    'alignment evaluation set and the Alignment Moonshot thought leadership goals. Further research '
                    'directions: look for benchmark results, model comparisons, or evaluation methodology discussions.'
                ),
            },
            {
                "id": 'q11_2',
                "title": 'Goal alignment research progress',
                "search_terms": 'goal alignment decision context',
                "goals": (
                    'Find any work related to the decision context problem, goal alignment evaluation, or research essays '
                    'published or drafted in the last week. This connects directly to the Alignment Moonshot goals (3 '
                    'research essays, book proposal, official eval set, thought leadership). Additional research '
                    'directions: check for draft essays, academic paper progress, or co-authorship work with the external collaborator.'
                ),
            },
            {
                "id": 'q11_3',
                "title": "the research lead's essay and Alignment Moonshot thought leadership",
                "search_terms": 'essay thought leadership',
                "goals": (
                    "The goal of this query is to surface any internal records about the research lead's essay noted by a research colleague on "
                    'May 25, 2026, including its publication status, content themes, and how it connects to the Alignment '
                    'Moonshot goal of establishing Convictional as a thought leader in AI for business decisions. Once '
                    "results are found, cross-reference with the 'Publish 3 timely research essays' and 'Build the "
                    "official goal alignment evaluation set' subgoals. Additional research directions: determine whether "
                    'the essay has been submitted or published externally, identify any competitive SEO/GEO positioning '
                    'strategy discussed around it, and assess how it complements or overlaps with the co-authored piece '
                    'with the external collaborator.'
                ),
            },
            {
                "id": 'q11_4',
                "title": "the research lead's essay feedback and publishing timeline",
                "search_terms": '"Slack MCP" essay feedback',
                "goals": (
                    "The goal is to surface any feedback the research lead has received on the 'Slack + MCP won't cut it' essay draft "
                    'since it was shared with colleagues during the week of May 18-22, and to determine the current '
                    'publishing timeline. Previous learnings confirm the essay exists and was awaiting additional feedback '
                    'before a second pass. Further research should look for: any reviewer comments or suggested revisions, '
                    'whether a second draft has been completed, and where this sits in the queue for the Alignment '
                    'Moonshot publishing goal of 3 timely research essays. Also look for any connections to the YC '
                    'competitor SEO/GEO alignment feedback a research colleague provided on May 25.'
                ),
            },
            {
                "id": 'q11_5',
                "title": 'Alignsim condition 3, Slack+MCP essay, and Gemma write-up status',
                "search_terms": '"Alignsim" "Slack MCP" "Gemma" research sync',
                "goals": (
                    'The goal of this query is to find the current status of the three active research tracks the research lead was '
                    'advancing during the week of May 25, 2026: (1) Alignsim condition 3 multi-agent teams experiment — '
                    'specifically whether results have been collected and what feedback from the research sync the research lead was '
                    'planning to implement; (2) the Slack + MCP essay — whether it has been finalized, published, and what '
                    'reception or feedback came from additional reviewers; and (3) the Gemma learning extraction write-up '
                    '— whether it has been completed and whether the subsequent phase of evaluating actual research '
                    'reports with extracted learnings has begun. These three tracks are directly tied to the Alignment '
                    'Moonshot goals (3 timely research essays, official goal alignment eval set, thought leadership) and '
                    "the organization's core research mission. Once results are found, additional research directions "
                    'include: checking for any new experiment results from Alignsim condition 3, looking for published or '
                    'drafted versions of the Slack+MCP essay, and identifying whether the Gemma evaluation pipeline has '
                    'produced any preliminary findings.'
                ),
            },
        ],
    },
    {
        "id": 'q13_recent_sales_conversations',
        "topic": 'Give me a summary of recent sales conversations and notes from within the last few weeks.',
        "queries": [
            {
                "id": 'q13_0',
                "title": 'Recent Sales Conversations',
                "search_terms": 'sales conversations',
                "goals": (
                    'Retrieve recent sales conversations from the last few weeks to provide the research lead with a summary of ongoing '
                    'and recent sales activity. Look for themes, key prospects, objections raised, and deal stages. '
                    'Further research should focus on identifying patterns in customer interest, common pain points '
                    'mentioned, and which prospects are most engaged.'
                ),
            },
            {
                "id": 'q13_1',
                "title": 'Sales Notes & Deal Updates',
                "search_terms": 'sales notes deals',
                "goals": (
                    'Surface any sales notes, deal memos, or CRM-style notes logged in the last few weeks. The goal is to '
                    'understand the state of the pipeline and any notable developments. Follow-up directions: identify '
                    'which deals have progressed, which are stalled, and what next steps have been noted.'
                ),
            },
            {
                "id": 'q13_2',
                "title": 'Prospect Outreach & Follow-ups',
                "search_terms": 'prospect outreach follow-up',
                "goals": (
                    'Find records of prospect outreach and follow-up activity from the past few weeks. This supports '
                    'building a complete picture of where conversations stand in the sales funnel. Additional research '
                    'directions: identify which ICPs (remote tech companies, 50-200 people, CEO with coach, etc.) are '
                    "being targeted and how they are responding to Convictional's value proposition around the decision "
                    'context problem.'
                ),
            },
            {
                "id": 'q13_3',
                "title": 'ICP objections and conversion blockers in recent deals',
                "search_terms": 'objections blockers pipeline conversion',
                "goals": (
                    'The goal is to identify the most common objections and conversion blockers surfaced across recent '
                    'sales conversations — particularly around Microsoft email dependency, incumbent-wiki entrenchment, '
                    'chat-tool loyalty, and build-in-house bias. (The original planner output named the specific '
                    'prospects and the individuals at each; those have been removed for publication and replaced with '
                    'the objection category alone.) Understanding which prospect segments are most '
                    'resistant versus most receptive will help prioritize follow-up and sharpen positioning. Once patterns '
                    'are identified, additional research should explore: (1) which ICP-matching prospects (remote tech, '
                    '50-200 people, CEO with coach, uses Gmail) have the fewest blockers and are closest to a trial or '
                    "deal; (2) how Convictional's differentiated positioning around the decision context problem and "
                    "AI-native goal alignment can directly counter the 'we'll build it in-house with Claude' objection; "
                    'and (3) which prospects — especially those from recent conference and trip-week outreach — have '
                    'confirmed next steps, trials underway, or warm intros pending.'
                ),
            },
            {
                "id": 'q13_4',
                "title": 'Conference handshake deal onboarding & pipeline next steps',
                "search_terms": 'conference onboarding deal pipeline',
                "goals": (
                    'Surface details on the handshake ICP deal closed at a startup conference in May 2026, '
                    'including whether the customer has onboarded and any next steps logged. Also identify which '
                    'trip-week prospects have active next steps scheduled and what collateral or '
                    'enablement has been sent. Additionally, look for patterns across misaligned prospects '
                    'to sharpen ICP disqualification criteria. (Named prospects and contacts have been removed for '
                    'publication.) Once results are found, '
                    'cross-reference deal stages: categorize contacts as progressed, stalled, or pending, and note any '
                    'recurring blockers (e.g. Microsoft email, build-in-house bias, early-stage wartime mode) that could '
                    'inform earlier disqualification in the sales process.'
                ),
            },
            {
                "id": 'q13_5',
                "title": 'In-person dinner and tech-week pipeline events',
                "search_terms": 'dinner tech week pipeline events',
                "goals": (
                    'The goal of this research is to surface details about two upcoming in-person events (a prospect '
                    "dinner and a city tech week) being used to accelerate Convictional's sales pipeline — specifically "
                    'confirmed attendees, prospect invitations, and any deal-acceleration strategy tied to these events. '
                    'Previous research has covered most individual prospect calls and the earlier conference follow-up '
                    'cadence. What remains underexplored is the '
                    'logistics and pipeline strategy around these upcoming in-person events. Once results are found, '
                    'further research should focus on: (1) which prospects from the recent pipeline have been invited or '
                    'confirmed for either event; (2) what enablement '
                    'materials (positioning docs, one-pagers, demo scripts) are being prepared for event follow-ups; (3) '
                    'how the earlier launch event connects to or feeds into these later events. (Named prospects, '
                    'contacts, and event names have been removed for publication.)'
                ),
            },
        ],
    },
]

# Active prompt set. Swap to ITERATION_PROMPTS to re-run on the original 5 (for traceability).
PROMPTS = HOLDOUT_PROMPTS
