/* Decisions → Goals 3×3 mapping explorer.
   Reads window.CELL_DATA (generated by export_graph.py) and renders the
   selected condition×schema cell with 3d-force-graph. */
(function () {
  "use strict";

  const DATA = window.CELL_DATA;
  if (!DATA) {
    document.getElementById("placeholder").textContent =
      "cell_data.js not loaded. Run: PYTHONPATH=. uv run python -m decisions_to_goals.viz.export_graph";
    return;
  }

  const COLORS = {
    decision: "#2f9bdf",
    goalStated: "#f5b301",
    goalUnstated: "#e8743b",
    goalOrphan: "#6b7280",    // synthetic orphan bucket — grey, visually distinct
    goalUnknown: "#9aa4b0",
  };

  // Relation → edge color (GM uses the full vocabulary; DM/DSM use maps_to/scored).
  const RELATION_COLORS = {
    maps_to: "#5bc88a",
    scored: "#5bc88a",
    advances: "#5bc88a",
    informs: "#4aa3df",
    is_evidence_of: "#33c6c0",
    depends_on: "#9b8cff",
    synergizes_with: "#74e39b",
    supersedes: "#9aa4b0",
    blocks: "#ef5f5f",
    tensions_with: "#f0883e",
    unattached: "#4b5563",    // orphan decision → orphan goal
  };
  const DEFAULT_LINK_COLOR = "#5b6675";

  function nodeColor(n) {
    if (n.type === "decision") return COLORS.decision;
    if (n.orphan === true) return COLORS.goalOrphan;
    if (n.stated === true) return COLORS.goalStated;
    if (n.stated === false) return COLORS.goalUnstated;
    return COLORS.goalUnknown;
  }

  function linkColor(l) {
    return RELATION_COLORS[l.relation] || DEFAULT_LINK_COLOR;
  }

  function esc(s) {
    return String(s).replace(/[&<>"]/g, (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])
    );
  }

  // ── Graph instance ──────────────────────────────────────────────────────────
  let particlesOn = true;

  const Graph = ForceGraph3D()(document.getElementById("graph"))
    .backgroundColor("#0e1116")
    .nodeColor(nodeColor)
    .nodeOpacity(0.9)
    .nodeVal((n) => n.__val || 1)
    .nodeLabel((n) => {
      const kind = n.type === "goal"
        ? `goal · ${n.orphan === true ? "orphan bucket" : n.stated === true ? "stated" : n.stated === false ? "unstated" : "unmapped"}`
        : "decision";
      return `<div style="max-width:320px"><b>${esc(n.full)}</b><br><span style="color:#8b949e">${kind}</span></div>`;
    })
    .linkColor(linkColor)
    .linkOpacity(0.45)
    .linkWidth((l) => 0.5 + 3 * (l.value || 0.3))
    .linkLabel((l) => `${esc(l.relation)}${l.label && l.label !== l.relation ? " · " + esc(l.label) : ""}`)
    .linkDirectionalArrowLength(3.5)
    .linkDirectionalArrowRelPos(1)
    .linkDirectionalParticles((l) => (particlesOn ? 2 : 0))
    .linkDirectionalParticleWidth((l) => 1 + 2 * (l.value || 0.3))
    .onNodeClick((node) => {
      // Fly camera to the clicked node
      const dist = 80;
      const ratio = 1 + dist / Math.hypot(node.x || 1, node.y || 1, node.z || 1);
      Graph.cameraPosition(
        { x: (node.x || 0) * ratio, y: (node.y || 0) * ratio, z: (node.z || 0) * ratio },
        node,
        1200
      );
    });

  // ── Selection ─────────────────────────────────────────────────────────────
  let activeCellId = null;

  function selectCell(cellId) {
    const cell = DATA.cells[cellId];
    if (!cell) return;
    activeCellId = cellId;

    // Clone so the force engine's mutation of source/target doesn't corrupt the cache
    const degree = {};
    cell.links.forEach((l) => {
      degree[l.source] = (degree[l.source] || 0) + 1;
      degree[l.target] = (degree[l.target] || 0) + 1;
    });
    const nodes = cell.nodes.map((n) => ({
      ...n,
      __val: (n.type === "goal" ? 4 : 1) + Math.min(8, (degree[n.id] || 0) * 0.4),
    }));
    const links = cell.links.map((l) => ({ ...l }));

    Graph.graphData({ nodes, links });

    document.getElementById("placeholder").style.display = "none";
    const hud = document.getElementById("hud");
    hud.style.display = "block";
    hud.innerHTML =
      `<div class="cellname">${esc(cell.condition_label)} × ${esc(cell.schema_label)}</div>` +
      `${cell.meta.n_decisions} decisions · ${cell.meta.n_goals} goals · ${cell.meta.n_links} links`;

    document.getElementById("selname").textContent =
      `${cell.condition_label} × ${cell.schema_label}`;
    document.getElementById("counts").innerHTML =
      `<b>${cell.meta.n_decisions}</b> connected decisions · ` +
      `<b>${cell.meta.n_goals}</b> goals (of ${cell.meta.goals_in_set} in set) · ` +
      `<b>${cell.meta.n_links}</b> links`;

    document.querySelectorAll("td.cell").forEach((td) => {
      td.classList.toggle("active", td.dataset.cellId === cellId);
    });

    // Frame the whole graph after the layout warms up
    setTimeout(() => Graph.zoomToFit(600, 60), 400);
  }

  // ── Build the 3×3 matrix table ──────────────────────────────────────────────
  function buildMatrix() {
    const table = document.getElementById("matrix");
    const headRow = document.createElement("tr");
    headRow.innerHTML = `<th class="rowhead"></th>` +
      DATA.schemas.map((s) => `<th>${esc((DATA.schema_labels[s] || s).replace(/ \(.*\)/, ""))}</th>`).join("");
    table.appendChild(headRow);

    DATA.conditions.forEach((cond) => {
      const tr = document.createElement("tr");
      const th = document.createElement("th");
      th.className = "rowhead";
      th.textContent = DATA.condition_labels[cond] || cond;
      tr.appendChild(th);

      DATA.schemas.forEach((schema) => {
        const td = document.createElement("td");
        const cellId = Object.keys(DATA.cells).find(
          (k) => DATA.cells[k].condition === cond && DATA.cells[k].schema === schema
        );
        if (!cellId) {
          td.innerHTML = `<button disabled style="color:#5b6675">—</button>`;
        } else {
          td.className = "cell";
          td.dataset.cellId = cellId;
          const m = DATA.cells[cellId].meta;
          const btn = document.createElement("button");
          btn.innerHTML = `${schema.toUpperCase()}<span class="count">${m.n_links} links</span>`;
          btn.addEventListener("click", () => selectCell(cellId));
          td.appendChild(btn);
        }
        tr.appendChild(td);
      });
      table.appendChild(tr);
    });
  }

  buildMatrix();

  // ── Controls ────────────────────────────────────────────────────────────────
  document.getElementById("toggleParticles").addEventListener("change", (e) => {
    particlesOn = e.target.checked;
    Graph.linkDirectionalParticles(Graph.linkDirectionalParticles());
  });
  document.getElementById("resetView").addEventListener("click", () => Graph.zoomToFit(600, 60));

  // Auto-select mixed + GM (richest condition × richest schema) as default, else first available.
  const initial = DATA.cells["mixed__gm"] ? "mixed__gm" : Object.keys(DATA.cells)[0];
  selectCell(initial);
})();
